### ISSUE TITLE
Question about the argument "border" in the function utility.root_mean_sqrt_error()

### ISSUE THREAD

**Issue by kjy09** [zhwzhong/DAGF#4]
Hi,

I am impressed by this work. But when I was reading the source code, I was confused by the argument "border" in the function utility.root_mean_sqrt_error(). When training and validating the model, "border" is set to 0 while it is set to 6 to test the model. Why is this argument set to different values for training/validation and test?

**Comment by zhwzhong** [comment]
hello, 
     Thanks for your attention, Removing the outer 6 pixels during testing is a common approach in the field, and the choice has minimal impact on training outcomes. 

Zhiwei Zhong

**Comment by kjy09** [comment]
> hello, Thanks for your attention, Removing the outer 6 pixels during testing is a common approach in the field, and the choice has minimal impact on training outcomes.
> 
> Zhiwei Zhong

Many thanks for your reply.
